-- Billing System Relational Schema (branch-aware)

CREATE TABLE IF NOT EXISTS branches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NULL,
  is_active TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_branch_name (name),
  UNIQUE KEY uniq_branch_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(32) PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  name VARCHAR(120) NULL,
  branch_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active TINYINT NOT NULL DEFAULT 1,
  UNIQUE KEY uniq_username (username),
  KEY idx_users_branch (branch_id),
  CONSTRAINT fk_users_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_number VARCHAR(20) NOT NULL,
  branch_id INT NOT NULL,
  first_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NULL,
  name VARCHAR(200) NULL,
  email VARCHAR(150) NULL,
  mobile VARCHAR(32) NULL,
  mobile_raw VARCHAR(32) NULL,
  street VARCHAR(150) NULL,
  barangay VARCHAR(150) NULL,
  municipality VARCHAR(150) NULL,
  province VARCHAR(150) NULL,
  area VARCHAR(150) NULL,
  map_pin VARCHAR(50) NULL,
  status VARCHAR(30) NULL,
  remarks TEXT NULL,
  since VARCHAR(50) NULL,
  activation_date DATE NULL,
  plan_id VARCHAR(80) NULL,
  plan_name VARCHAR(120) NULL,
  plan_amount DECIMAL(12, 2) NULL,
  plan_billing VARCHAR(30) NULL,
  plan_category VARCHAR(20) NULL,
  scheduled_plan_id VARCHAR(80) NULL,
  scheduled_plan_name VARCHAR(120) NULL,
  scheduled_plan_amount DECIMAL(12, 2) NULL,
  scheduled_plan_billing VARCHAR(30) NULL,
  scheduled_plan_category VARCHAR(20) NULL,
  scheduled_plan_apply_at DATETIME NULL,
  scheduled_pppoe_profile VARCHAR(120) NULL,
  bill_date DATE NULL,
  due_date DATE NULL,
  prepaid_expiration_at DATETIME NULL,
  due_offset INT NULL,
  credit_limit DECIMAL(12, 2) NULL,
  login_username VARCHAR(120) NULL,
  login_password_hash VARCHAR(255) NULL,
  pppoe_mode VARCHAR(30) NULL,
  mikrotik_id VARCHAR(120) NULL,
  pppoe_username VARCHAR(120) NULL,
  pppoe_password VARCHAR(120) NULL,
  pppoe_profile VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_account_number (account_number),
  KEY idx_customers_branch (branch_id),
  KEY idx_customers_branch_plan (branch_id, plan_id),
  KEY idx_customers_branch_scheduled_plan (branch_id, scheduled_plan_apply_at),
  KEY idx_customers_area (area),
  CONSTRAINT fk_customers_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS plans (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  plan_id VARCHAR(80) NOT NULL,
  name VARCHAR(120) NULL,
  label VARCHAR(120) NULL,
  category VARCHAR(20) NULL,
  description TEXT NULL,
  profile VARCHAR(120) NULL,
  profile_bindings LONGTEXT NULL,
  price DECIMAL(12, 2) NULL,
  price_suffix VARCHAR(40) NULL,
  validity INT NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uniq_branch_plan (branch_id, plan_id),
  KEY idx_plans_branch (branch_id),
  CONSTRAINT fk_plans_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS coverage_areas (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  category VARCHAR(50) NULL,
  lat DECIMAL(10, 6) NULL,
  lng DECIMAL(10, 6) NULL,
  status VARCHAR(30) NULL,
  notes TEXT NULL,
  area_code VARCHAR(50) NULL,
  mikrotik_id VARCHAR(120) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uniq_branch_area (branch_id, name),
  KEY idx_coverage_branch (branch_id),
  CONSTRAINT fk_coverage_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pon_olts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  client_uid VARCHAR(80) NOT NULL,
  name VARCHAR(150) NOT NULL,
  technology VARCHAR(20) NOT NULL,
  site VARCHAR(180) NULL,
  status VARCHAR(30) NULL,
  pon_ports INT NOT NULL DEFAULT 16,
  pon_code_prefix VARCHAR(40) NOT NULL DEFAULT 'PON',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_pon_olts_branch_uid (branch_id, client_uid),
  UNIQUE KEY uniq_pon_olts_branch_name (branch_id, name),
  KEY idx_pon_olts_branch (branch_id),
  CONSTRAINT fk_pon_olts_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pon_naps (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  olt_id BIGINT NOT NULL,
  client_uid VARCHAR(80) NOT NULL,
  code VARCHAR(180) NOT NULL,
  area VARCHAR(180) NULL,
  coordinate VARCHAR(120) NULL,
  splitter VARCHAR(20) NOT NULL,
  pon_ref VARCHAR(40) NOT NULL,
  pon_capacity INT NOT NULL DEFAULT 64,
  capacity INT NOT NULL DEFAULT 16,
  used INT NOT NULL DEFAULT 0,
  optical_power VARCHAR(80) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_pon_naps_branch_uid (branch_id, client_uid),
  UNIQUE KEY uniq_pon_naps_branch_code (branch_id, code),
  KEY idx_pon_naps_branch_olt (branch_id, olt_id),
  KEY idx_pon_naps_pon_ref (pon_ref),
  CONSTRAINT fk_pon_naps_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_pon_naps_olt FOREIGN KEY (olt_id) REFERENCES pon_olts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pon_nap_connections (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nap_id BIGINT NOT NULL,
  customer_account_number VARCHAR(20) NULL,
  customer_name VARCHAR(200) NULL,
  customer_ref VARCHAR(200) NULL,
  port INT NOT NULL,
  optical_info VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_pon_connection_port (nap_id, port),
  KEY idx_pon_connection_customer (customer_account_number),
  CONSTRAINT fk_pon_connections_nap FOREIGN KEY (nap_id) REFERENCES pon_naps(id) ON DELETE CASCADE,
  CONSTRAINT fk_pon_connections_customer FOREIGN KEY (customer_account_number) REFERENCES customers(account_number) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collector_assignments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  coverage_id BIGINT NULL,
  area_name VARCHAR(150) NULL,
  collector_user_id VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_assign_branch (branch_id),
  KEY idx_assign_collector (collector_user_id),
  CONSTRAINT fk_assign_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_assign_collector FOREIGN KEY (collector_user_id) REFERENCES users(id),
  CONSTRAINT fk_assign_coverage FOREIGN KEY (coverage_id) REFERENCES coverage_areas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_entries (
  id VARCHAR(64) PRIMARY KEY,
  branch_id INT NOT NULL,
  account_number VARCHAR(20) NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  date DATE NULL,
  kind VARCHAR(20) NULL,
  direction VARCHAR(10) NULL,
  reference VARCHAR(32) NULL,
  or_number VARCHAR(20) NULL,
  description TEXT NULL,
  type VARCHAR(20) NULL,
  recorded_at DATETIME NULL,
  recorded_by_user_id VARCHAR(32) NULL,
  recorded_by_username VARCHAR(100) NULL,
  recorded_by_name VARCHAR(100) NULL,
  recorded_by_role VARCHAR(30) NULL,
  payer VARCHAR(100) NULL,
  status VARCHAR(30) NULL,
  payment_method VARCHAR(40) NULL,
  fingerprint VARCHAR(200) NULL,
  xendit_id VARCHAR(120) NULL,
  KEY idx_payments_branch_account (branch_id, account_number),
  KEY idx_payments_reference (reference),
  KEY idx_payments_or_number (or_number),
  KEY idx_payments_fingerprint (fingerprint),
  KEY idx_payments_recorded (recorded_at),
  CONSTRAINT fk_payments_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_payments_customer FOREIGN KEY (account_number) REFERENCES customers(account_number) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_confirmation_queue (
  id VARCHAR(64) PRIMARY KEY,
  branch_id INT NOT NULL,
  account_number VARCHAR(20) NOT NULL,
  customer_name VARCHAR(200) NULL,
  amount DECIMAL(12, 2) NULL,
  reference VARCHAR(64) NULL,
  payment_method VARCHAR(40) NULL,
  notes TEXT NULL,
  payment_date DATETIME NULL,
  proof_image_url VARCHAR(255) NOT NULL,
  proof_mime VARCHAR(100) NOT NULL,
  proof_original_name VARCHAR(255) NULL,
  proof_sha256 CHAR(64) NULL,
  proof_analysis_json LONGTEXT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at DATETIME NULL,
  reviewed_by_user_id VARCHAR(32) NULL,
  reviewed_by_username VARCHAR(100) NULL,
  reviewed_by_name VARCHAR(120) NULL,
  decision_reason TEXT NULL,
  payment_entry_id VARCHAR(64) NULL,
  reviewed_amount DECIMAL(12, 2) NULL,
  reviewed_reference VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_pcq_branch_status_submitted (branch_id, status, submitted_at),
  KEY idx_pcq_branch_account (branch_id, account_number),
  KEY idx_pcq_branch_proof_hash (branch_id, proof_sha256),
  KEY idx_pcq_payment_entry (payment_entry_id),
  CONSTRAINT fk_pcq_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_draft_submissions (
  id VARCHAR(64) PRIMARY KEY,
  branch_id INT NOT NULL,
  submitted_by_user_id VARCHAR(32) NOT NULL,
  submitted_by_username VARCHAR(100) NULL,
  submitted_by_name VARCHAR(120) NULL,
  customer_name VARCHAR(200) NULL,
  contact_number VARCHAR(50) NULL,
  plan_name VARCHAR(120) NULL,
  area_name VARCHAR(150) NULL,
  address_text VARCHAR(255) NULL,
  draft_account_number VARCHAR(20) NULL,
  draft_json LONGTEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at DATETIME NULL,
  reviewed_by_user_id VARCHAR(32) NULL,
  reviewed_by_username VARCHAR(100) NULL,
  reviewed_by_name VARCHAR(120) NULL,
  decision_reason TEXT NULL,
  approved_customer_account_number VARCHAR(20) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_cds_branch_status_submitted (branch_id, status, submitted_at),
  KEY idx_cds_branch_submitter (branch_id, submitted_by_user_id, submitted_at),
  KEY idx_cds_draft_account_number (draft_account_number),
  KEY idx_cds_plan_name (plan_name),
  CONSTRAINT fk_cds_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_archives (
  id VARCHAR(64) PRIMARY KEY,
  branch_id INT NOT NULL,
  account_number VARCHAR(20) NOT NULL,
  customer_name VARCHAR(200) NULL,
  contact_number VARCHAR(50) NULL,
  plan_name VARCHAR(120) NULL,
  area_name VARCHAR(150) NULL,
  payment_entry_count INT NOT NULL DEFAULT 0,
  ticket_count INT NOT NULL DEFAULT 0,
  job_count INT NOT NULL DEFAULT 0,
  sms_message_count INT NOT NULL DEFAULT 0,
  deleted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  purge_after DATETIME NOT NULL,
  deleted_by_user_id VARCHAR(32) NULL,
  deleted_by_username VARCHAR(100) NULL,
  deleted_by_name VARCHAR(120) NULL,
  payload_json LONGTEXT NOT NULL,
  proof_file_paths_json LONGTEXT NULL,
  restored_at DATETIME NULL,
  restored_by_user_id VARCHAR(32) NULL,
  restored_by_username VARCHAR(100) NULL,
  restored_by_name VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_customer_archives_branch_deleted (branch_id, deleted_at),
  KEY idx_customer_archives_branch_purge (branch_id, purge_after),
  KEY idx_customer_archives_branch_account (branch_id, account_number),
  CONSTRAINT fk_customer_archives_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  subject VARCHAR(200) NULL,
  description TEXT NULL,
  customer_name VARCHAR(200) NULL,
  account_number VARCHAR(20) NULL,
  contact VARCHAR(50) NULL,
  status VARCHAR(20) NULL,
  assigned_to VARCHAR(120) NULL,
  source VARCHAR(20) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  history_job_id BIGINT NULL,
  history_job_created_at DATETIME NULL,
  ticket_number VARCHAR(50) NULL,
  KEY idx_tickets_branch (branch_id),
  KEY idx_tickets_account (account_number),
  KEY idx_tickets_number (ticket_number),
  CONSTRAINT fk_tickets_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  job_number BIGINT NULL,
  branch_id INT NOT NULL,
  type VARCHAR(50) NULL,
  technician VARCHAR(120) NULL,
  priority VARCHAR(20) NULL,
  schedule DATETIME NULL,
  appointment_end DATETIME NULL,
  sla_due_at DATETIME NULL,
  status VARCHAR(20) NULL,
  workflow_status VARCHAR(30) NOT NULL DEFAULT 'unassigned',
  done_at DATETIME NULL,
  notes TEXT NULL,
  description TEXT NULL,
  customer_account_number VARCHAR(20) NULL,
  customer_name VARCHAR(200) NULL,
  customer_phone VARCHAR(50) NULL,
  service_address VARCHAR(500) NULL,
  latitude DECIMAL(10, 7) NULL,
  longitude DECIMAL(10, 7) NULL,
  plan_name VARCHAR(120) NULL,
  dispatch_payload_json LONGTEXT NULL,
  record_version INT NOT NULL DEFAULT 1,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  ticket_id BIGINT NULL,
  ticket_number VARCHAR(50) NULL,
  ticket_subject VARCHAR(200) NULL,
  origin VARCHAR(50) NULL,
  KEY idx_jobs_branch (branch_id),
  KEY idx_jobs_ticket (ticket_id),
  KEY idx_jobs_branch_workflow (branch_id, workflow_status, schedule),
  KEY idx_jobs_branch_technician (branch_id, technician, workflow_status),
  KEY idx_jobs_customer_account (customer_account_number),
  CONSTRAINT fk_jobs_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_jobs_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS technician_job_events (
  id VARCHAR(100) PRIMARY KEY,
  branch_id INT NOT NULL,
  job_id BIGINT NULL,
  job_number VARCHAR(50) NULL,
  event_type VARCHAR(40) NULL,
  from_status VARCHAR(30) NULL,
  to_status VARCHAR(30) NULL,
  actor_type VARCHAR(30) NULL,
  actor_id VARCHAR(80) NULL,
  actor_name VARCHAR(160) NULL,
  client_event_id VARCHAR(100) NULL,
  payload_json LONGTEXT NULL,
  event_at DATETIME NOT NULL,
  UNIQUE KEY uq_job_events_branch_client (branch_id, client_event_id),
  KEY idx_job_events_branch_job_time (branch_id, job_id, event_at),
  CONSTRAINT fk_job_events_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_events_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_logs (
  id VARCHAR(32) PRIMARY KEY,
  branch_id INT NOT NULL,
  message TEXT NULL,
  meta TEXT NULL,
  timestamp DATETIME NULL,
  user_id VARCHAR(32) NULL,
  username VARCHAR(120) NULL,
  KEY idx_logs_branch (branch_id),
  KEY idx_logs_user (user_id),
  CONSTRAINT fk_logs_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS business_profiles (
  branch_id INT PRIMARY KEY,
  business_name VARCHAR(200) NULL,
  tagline VARCHAR(200) NULL,
  support_email VARCHAR(150) NULL,
  contact VARCHAR(50) NULL,
  address VARCHAR(250) NULL,
  logo_base64 LONGTEXT NULL,
  updated_at DATETIME NULL,
  CONSTRAINT fk_business_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS integration_settings (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  provider VARCHAR(50) NOT NULL,
  secret_json LONGTEXT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_branch_provider (branch_id, provider),
  CONSTRAINT fk_integration_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sessions (
  session_id VARCHAR(64) PRIMARY KEY,
  user_id VARCHAR(32) NOT NULL,
  created_at BIGINT NOT NULL,
  KEY idx_sessions_user (user_id),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS sms_templates (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  content TEXT NOT NULL,
  channels VARCHAR(80) NULL,
  is_active TINYINT NOT NULL DEFAULT 1,
  created_by_user_id VARCHAR(32) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_sms_templates_branch_name (branch_id, name),
  KEY idx_sms_templates_branch (branch_id),
  KEY idx_sms_templates_active (is_active),
  CONSTRAINT fk_sms_templates_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_sms_templates_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sms_schedules (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  title VARCHAR(180) NOT NULL,
  recipient_type VARCHAR(20) NOT NULL DEFAULT 'subscriber',
  recipient_value TEXT NULL,
  recipient_identifier VARCHAR(200) NULL,
  message_text TEXT NOT NULL,
  delivery_methods VARCHAR(80) NOT NULL DEFAULT 'semaphore,mail',
  template_id BIGINT NULL,
  schedule_mode VARCHAR(30) NOT NULL DEFAULT 'custom',
  schedule_time DATETIME NULL,
  schedule_due_time VARCHAR(8) NULL,
  schedule_delay_days INT NOT NULL DEFAULT 0,
  repeat_mode VARCHAR(20) NOT NULL DEFAULT 'once',
  repeat_count INT NOT NULL DEFAULT 0,
  run_count INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_by_user_id VARCHAR(32) NULL,
  last_executed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sms_schedules_branch (branch_id),
  KEY idx_sms_schedules_status (status),
  KEY idx_sms_schedules_time (schedule_time),
  KEY idx_sms_schedules_template (template_id),
  CONSTRAINT fk_sms_schedules_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_sms_schedules_template FOREIGN KEY (template_id) REFERENCES sms_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_sms_schedules_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sms_messages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  schedule_id BIGINT NULL,
  provider VARCHAR(32) NOT NULL DEFAULT 'semaphore',
  recipient VARCHAR(255) NOT NULL,
  recipient_label VARCHAR(200) NULL,
  customer_account_number VARCHAR(20) NULL,
  recipient_area VARCHAR(150) NULL,
  sender_name VARCHAR(128) NULL,
  message_text TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  provider_message_id VARCHAR(120) NULL,
  provider_response TEXT NULL,
  error_message TEXT NULL,
  created_by_user_id VARCHAR(32) NULL,
  created_by_username VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_sms_branch_created (branch_id, created_at),
  KEY idx_sms_branch_status (branch_id, status),
  KEY idx_sms_account (customer_account_number),
  KEY idx_sms_schedule (schedule_id),
  CONSTRAINT fk_sms_messages_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_sms_messages_schedule FOREIGN KEY (schedule_id) REFERENCES sms_schedules(id) ON DELETE SET NULL,
  CONSTRAINT fk_sms_messages_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sms_automations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT NOT NULL,
  name VARCHAR(180) NOT NULL,
  trigger_event VARCHAR(80) NOT NULL,
  timing VARCHAR(80) NOT NULL DEFAULT 'immediate',
  channels VARCHAR(80) NOT NULL DEFAULT 'sms,email',
  template_id BIGINT NULL,
  message_text TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_by_user_id VARCHAR(32) NULL,
  last_triggered_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_sms_automations_branch_name (branch_id, name),
  KEY idx_sms_automations_branch (branch_id),
  KEY idx_sms_automations_trigger (trigger_event),
  KEY idx_sms_automations_status (status),
  KEY idx_sms_automations_template (template_id),
  CONSTRAINT fk_sms_automations_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_sms_automations_template FOREIGN KEY (template_id) REFERENCES sms_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_sms_automations_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sms_automation_runs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  automation_id BIGINT NOT NULL,
  branch_id INT NOT NULL,
  customer_account_number VARCHAR(20) NULL,
  recipient VARCHAR(64) NULL,
  delivery_method VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  error_message TEXT NULL,
  payload TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_sms_runs_automation (automation_id),
  KEY idx_sms_runs_branch_status (branch_id, status),
  KEY idx_sms_runs_created (created_at),
  KEY idx_sms_runs_account (customer_account_number),
  CONSTRAINT fk_sms_runs_automation FOREIGN KEY (automation_id) REFERENCES sms_automations(id) ON DELETE CASCADE,
  CONSTRAINT fk_sms_runs_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_sms_runs_account FOREIGN KEY (customer_account_number) REFERENCES customers(account_number) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_expenses (
  id VARCHAR(80) PRIMARY KEY,
  branch_id INT NOT NULL,
  expense_date DATE NOT NULL,
  category VARCHAR(80) NOT NULL,
  payee VARCHAR(160) NULL,
  vendor VARCHAR(160) NULL,
  description TEXT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  payment_method VARCHAR(30) NOT NULL DEFAULT 'other',
  reference_number VARCHAR(120) NULL,
  receipt_url VARCHAR(500) NULL,
  receipt_name VARCHAR(180) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'paid',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  approved_at DATETIME NULL,
  created_by_user_id VARCHAR(32) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(120) NULL,
  updated_by_user_id VARCHAR(32) NULL,
  updated_by_username VARCHAR(100) NULL,
  updated_by_name VARCHAR(120) NULL,
  approved_by_user_id VARCHAR(32) NULL,
  approved_by_username VARCHAR(100) NULL,
  approved_by_name VARCHAR(120) NULL,
  KEY idx_fin_exp_branch_date (branch_id, expense_date),
  KEY idx_fin_exp_branch_category (branch_id, category),
  KEY idx_fin_exp_branch_status (branch_id, status, expense_date),
  CONSTRAINT fk_fin_exp_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_payroll (
  id VARCHAR(80) PRIMARY KEY,
  branch_id INT NOT NULL,
  pay_date DATE NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  employee_name VARCHAR(140) NOT NULL,
  role VARCHAR(120) NULL,
  rate_per_day DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  gross_pay DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  deductions DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  net_pay DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  notes TEXT NULL,
  submitted TINYINT NOT NULL DEFAULT 0,
  submitted_at DATETIME NULL,
  attendance_json LONGTEXT NULL,
  attendance_summary_json LONGTEXT NULL,
  debts_json LONGTEXT NULL,
  debt_total DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  debt_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by_user_id VARCHAR(32) NULL,
  created_by_username VARCHAR(100) NULL,
  created_by_name VARCHAR(120) NULL,
  KEY idx_fin_payroll_branch_paydate (branch_id, pay_date),
  KEY idx_fin_payroll_branch_submitted (branch_id, submitted, submitted_at),
  KEY idx_fin_payroll_branch_period (branch_id, period_start, period_end),
  CONSTRAINT fk_fin_payroll_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_store (
  store_key VARCHAR(128) NOT NULL PRIMARY KEY,
  payload LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS app_download_assets (
  slot TINYINT NOT NULL,
  asset_kind VARCHAR(10) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  file_size BIGINT NOT NULL,
  file_blob LONGBLOB NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (slot, asset_kind)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
