const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const {
  findDuplicateIssues,
  findRuntimeIssues,
  loadFlavor,
  normalizeFlavorName,
  projectRoot
} = require('./flavor-tools');

const flavorsDir = path.join(projectRoot, 'flavors');
const tmpDir = path.join(projectRoot, '.tmp', 'flavors');

const rawArgs = process.argv.slice(2);
const flavorName = String(rawArgs.find((arg) => !arg.startsWith('--')) || '').trim();
const disableTunnel = rawArgs.includes('--no-tunnel');

function quoteYaml(value) {
  return `'${String(value || '').replace(/'/g, "''")}'`;
}

function writeCloudflaredConfig(name, flavor) {
  const config = flavor.cloudflared || {};
  const hostname = String(config.hostname || '').trim();
  const tunnel = String(config.tunnel || '').trim();
  const credentialsFile = String(config.credentialsFile || '').trim();
  if (!hostname || !tunnel || !credentialsFile) return '';

  const flavorTmpDir = path.join(tmpDir, name);
  fs.mkdirSync(flavorTmpDir, { recursive: true });
  const configPath = path.join(flavorTmpDir, 'cloudflared.yml');
  const service = String(config.service || `http://localhost:${flavor.app?.port || 3000}`).trim();
  const lines = [
    `# Generated by scripts/start-flavor.js for ${name}.`,
    `tunnel: ${quoteYaml(tunnel)}`,
    `credentials-file: ${quoteYaml(credentialsFile)}`,
    '',
    'ingress:',
    `  - hostname: ${quoteYaml(hostname)}`,
    `    service: ${quoteYaml(service)}`,
    '  - service: http_status:404',
    ''
  ];
  fs.writeFileSync(configPath, lines.join('\n'), 'utf8');
  return configPath;
}

function applyEnv(env, flavor) {
  const app = flavor.app || {};
  const upstream = flavor.customerUpstream || {};
  const storage = flavor.storage || {};
  const mysql = flavor.mysql || {};
  const secrets = flavor.secrets || {};
  const admin = flavor.initialAdmin || {};
  const businessProfile = flavor.businessProfile || {};
  const firebase = flavor.firebase || {};

  env.FLAVOR_RUNTIME_ISOLATED = '1';
  env.ACTIVE_FLAVOR_NAME = flavorName;
  env.STORAGE_DRIVER = String(storage.driver || storage.mode || 'mysql');
  env.NODE_ENV = String(app.nodeEnv || 'development');
  env.TZ = String(app.timezone || 'Asia/Manila');
  env.PORT = String(app.port || 3000);
  env.SESSION_COOKIE_NAME = String(app.sessionCookieName || `${flavorName}Session`);
  env.PUBLIC_BASE_URL = String(app.publicBaseUrl || `http://localhost:${env.PORT}`);
  env.CENTRAL_URL = String(app.centralUrl || env.PUBLIC_BASE_URL);
  env.APP_BASE_URL = String(app.appBaseUrl || env.PUBLIC_BASE_URL);

  env.ENABLE_CUSTOMER_UPSTREAM_STUB = upstream.enableStub === false ? 'false' : 'true';
  env.CUSTOMER_UPSTREAM_HOST = String(upstream.host || '127.0.0.1');
  env.CUSTOMER_UPSTREAM_PORT = String(upstream.port || 4002);
  env.CUSTOMER_UPSTREAM_URL = String(upstream.url || `http://${env.CUSTOMER_UPSTREAM_HOST}:${env.CUSTOMER_UPSTREAM_PORT}`);

  env.MYSQL_HOST = String(mysql.host || '127.0.0.1');
  env.MYSQL_PORT = String(mysql.port || 3306);
  env.MYSQL_USER = String(mysql.user || 'root');
  env.MYSQL_PASSWORD = String(mysql.password || '');
  env.MYSQL_DATABASE = String(mysql.database || '');
  env.MYSQL_CONN_LIMIT = String(mysql.connLimit || 10);

  env.CONFIG_MASTER_KEY = String(secrets.configMasterKey || '');
  env.SESSION_TOKEN_SECRET = String(secrets.sessionTokenSecret || '');
  env.INFO_API_USER = String(secrets.infoApiUser || 'collector-sync');
  env.INFO_API_PASS = String(secrets.infoApiPass || '');
  if (firebase.serviceAccountPath !== undefined) {
    env.FIREBASE_SERVICE_ACCOUNT_PATH = String(firebase.serviceAccountPath || '');
  }
  if (firebase.androidChannelId !== undefined) {
    env.FIREBASE_ANDROID_CHANNEL_ID = String(firebase.androidChannelId || '');
  }
  env.INITIAL_ADMIN_USERNAME = String(admin.username || 'archiecd');
  env.INITIAL_ADMIN_PASSWORD = String(admin.password || 'finley123!');
  env.INITIAL_BRANCH_NAME = String(admin.branchName || flavorName.toUpperCase());
  env.STRUCTURE_OWNER_ID = String(admin.structureOwnerId || '1');
  env.BUSINESS_NAME = String(businessProfile.businessName || admin.branchName || flavorName.toUpperCase());
  env.BUSINESS_SUPPORT_EMAIL = String(businessProfile.supportEmail || '');
  env.BUSINESS_CONTACT = String(businessProfile.contact || '');
  env.BUSINESS_ADDRESS = String(businessProfile.address || '');
  env.FLAVOR_FEATURES = JSON.stringify(flavor.features || {});

  const cloudflaredConfig = writeCloudflaredConfig(flavorName, flavor);
  if (cloudflaredConfig) {
    env.CLOUDFLARED_CONFIG = cloudflaredConfig;
    env.CLOUDFLARED_LOG = path.join(projectRoot, 'logs', `cloudflared-${flavorName}.log`);
  }
  if (disableTunnel) {
    env.DISABLE_CLOUDFLARED = '1';
  }
}

(async () => {
  const normalizedName = normalizeFlavorName(flavorName);
  const flavorPath = path.join(flavorsDir, `${normalizedName}.json`);
  if (!fs.existsSync(flavorPath)) {
    console.error(`Flavor not found: ${path.relative(projectRoot, flavorPath)}`);
    process.exit(1);
  }

  const duplicateIssues = findDuplicateIssues();
  const runtimeIssues = await findRuntimeIssues(normalizedName);
  const issues = [...duplicateIssues, ...runtimeIssues];
  if (issues.length) {
    console.error('[error] Flavor safety check failed:');
    issues.forEach((issue) => console.error(`- ${issue}`));
    process.exit(1);
  }

  const flavor = loadFlavor(normalizedName);
  const childEnv = { ...process.env };
  applyEnv(childEnv, flavor);

  const flavorLogDir = path.join(projectRoot, 'logs', normalizedName);
  fs.mkdirSync(flavorLogDir, { recursive: true });
  const serverLogPath = path.join(flavorLogDir, 'server.log');
  const serverErrPath = path.join(flavorLogDir, 'server.err.log');
  const serverLog = fs.createWriteStream(serverLogPath, { flags: 'a' });
  const serverErr = fs.createWriteStream(serverErrPath, { flags: 'a' });
  const startLine = `\n[${new Date().toISOString()}] Starting flavor ${normalizedName}\n`;
  serverLog.write(startLine);
  serverErr.write(startLine);

  console.log(`[info] Starting flavor: ${normalizedName}`);
  console.log(`[info] Local URL: http://localhost:${childEnv.PORT}`);
  console.log(`[info] Public URL: ${childEnv.PUBLIC_BASE_URL}`);
  console.log(`[info] Storage driver: ${childEnv.STORAGE_DRIVER}`);
  if (String(childEnv.STORAGE_DRIVER || '').trim().toLowerCase() !== 'json') {
    console.log(`[info] MySQL database: ${childEnv.MYSQL_DATABASE}`);
  }
  console.log(`[info] Runtime mode: isolated`);
  console.log(`[info] Server log: ${path.relative(projectRoot, serverLogPath)}`);

  const child = spawn(process.execPath, [path.join('scripts', 'start-with-info-api.js')], {
    cwd: projectRoot,
    env: childEnv,
    stdio: 'inherit',
    windowsHide: false
  });

  child.on('error', (error) => {
    const detail = `${error.message || error} code=${error.code || ''} errno=${error.errno || ''} syscall=${error.syscall || ''} path=${error.path || ''}`;
    console.error(`[error] Failed to start flavor ${normalizedName}: ${detail}`);
    serverErr.write(`[error] Failed to start flavor ${normalizedName}: ${detail}\n`);
    process.exit(1);
  });

  child.on('exit', (code) => {
    serverLog.end();
    serverErr.end();
    process.exit(code ?? 0);
  });
})().catch((error) => {
  console.error(`${error.message || error} code=${error.code || ''} errno=${error.errno || ''} syscall=${error.syscall || ''} path=${error.path || ''}`);
  process.exit(1);
});
