const assert = require('assert/strict');
const fs = require('fs');
const path = require('path');

const collectorRoot = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(collectorRoot, 'web', 'collectors.html'), 'utf8');
const browserSource = fs.readFileSync(path.join(collectorRoot, 'web', 'js', 'collectors-page.js'), 'utf8');
const stylesheet = fs.readFileSync(path.join(collectorRoot, 'web', 'css', 'collectors-tabler.css'), 'utf8');
const schemaSource = fs.readFileSync(path.join(collectorRoot, '..', '..', '..', 'scripts', 'schema.sql'), 'utf8');

const statusTabs = html.match(/data-collector-remittance-filter="(?:pending|remitted|rejected|archived)"/g) || [];
assert.equal(statusTabs.length, 4, 'all four remittance status tabs must remain available');
assert.match(html, /class="nav nav-tabs collector-remittance-tabs"/);
assert.match(html, /class="table table-vcenter table-nowrap card-table mb-0 collector-remittance-table"/);
assert.match(html, /<tbody id="collectorRemittanceList" aria-live="polite"><\/tbody>/);
assert.match(html, /id="collectorRemittanceReviewAudit" hidden/);
assert.doesNotMatch(html, /class="collector-remittance-list"/);

assert.match(browserSource, /document\.createElement\('tr'\)/);
assert.match(browserSource, /data-label="Collector"/);
assert.match(browserSource, /data-label="Status \/ Batch"/);
assert.match(browserSource, /data-collector-remittance-action="view"/);
assert.match(browserSource, /data-collector-remittance-action="delete"/);
assert.match(browserSource, /Delete Archived Remittance/);
assert.match(browserSource, /Deletion reason is required\./);
assert.match(browserSource, /Customer payments were preserved\./);
assert.match(browserSource, /collectorRemittanceReviewSubmit\.hidden = viewing/);
assert.match(browserSource, /\['view', 'confirm', 'reject', 'delete'\]\.includes\(action\)/);
assert.match(html, /id="collectorPaymentAmountEditModal"/);
assert.match(html, /id="collectorPaymentAmountEditExpectedAmount"/);
assert.match(html, /id="collectorPaymentAmountEditAuditHint"/);
assert.match(html, /id="assignMessage"[^>]+role="status"[^>]+aria-live="polite"[^>]+aria-atomic="true"/);
assert.match(html, /id="collectorGlobalMessage"[^>]+role="status"[^>]+aria-live="polite"[^>]+aria-atomic="true"/);
assert.match(html, /id="collectorPaymentAmountEditReason"[^>]+maxlength="500"[^>]+required/);
assert.match(html, /id="collectorPaymentRejectModal"/);
assert.match(browserSource, /data-collector-approval-action="edit-amount"/);
assert.match(browserSource, /method: 'PATCH'/);
assert.match(browserSource, /body: JSON\.stringify\(\{ amount, expectedAmount, reason \}\)/);
assert.match(browserSource, /Payment amount updated\. Review it before approval\./);
assert.match(browserSource, /window\.appToast\(msg, \{ type \}\)/);
assert.match(browserSource, /const fallbackHost = collectorGlobalMessage \|\| assignMessage/);
assert.match(browserSource, /fallbackToast\.textContent = String\(msg \?\? ''\)/);
assert.match(browserSource, /setCollectorPaymentAmountEditSaving\(true\)/);
assert.match(browserSource, /refreshResults\.some\(\(result\) => result !== true\)/);
assert.match(browserSource, /focusCollectorApprovalAfterAmountEdit\(safeEntryId\)/);
assert.match(browserSource, /const focusedSelectionId = document\.activeElement/);
assert.match(browserSource, /addEventListener\('keydown', containCollectorPaymentAmountEditFocus\)/);
assert.match(browserSource, /data-collector-approval-action="reject"/);
assert.match(html, /css\/collectors-tabler\.css\?v=2\.21/);
assert.match(html, /js\/collectors-page\.js\?v=3\.24/);
assert.doesNotMatch(browserSource, /collector-remittance-record__/);

assert.match(stylesheet, /\.collector-remittance-table\s*\{/);
assert.match(stylesheet, /\.collector-remittance-tabs \.nav-link\s*\{/);
assert.match(stylesheet, /\.collectors-tabler-modal\.collector-payment-amount-edit-modal/);
assert.match(stylesheet, /\.collector-global-message\s*\{/);
assert.match(stylesheet, /\.collector-global-message \.toast\s*\{/);
assert.doesNotMatch(stylesheet, /\.collector-remittance-record/);
assert.match(schemaSource, /CREATE TABLE IF NOT EXISTS collector_payment_amount_corrections/);
assert.match(schemaSource, /correction_order BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY/);
assert.match(schemaSource, /FOREIGN KEY \(payment_entry_id\) REFERENCES payment_entries\(id\) ON DELETE CASCADE/);

console.log('PASS compact remittance tabs plus audited payment amount edit and preserved reject actions');
